triggers:
- description: null
  envs: []
  last_enabled_at: 2024-06-09 13:10:14.758820+00:00
  name: Real-time predictions
  pipeline_uuid: predict
  schedule_interval: null
  schedule_type: api
  settings: null
  sla: null
  start_time: 2024-06-09 13:09:00+00:00
  status: active
  token: 47fb43204f9045e19b3b4e4472c725a6
  variables: {}
